name: C/C++ CI

on:
  push:
    branches: [ WUT ]
  pull_request:
    branches: [ WUT ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest

    steps:
    - uses: actions/checkout@v2
    - name: Update permissions
      run: chmod +rwx build.sh
    - name: Build
      run: ./build.sh
    - name: Upload files
      uses: actions/upload-artifact@v2
      with:
        name: Build
        path : |
          _sdCard
          _loadiine
    - name: Install 7zip
      run: apt-get install -y p7zip-full
    - name: Zip Files
      run: |
        cd _loadiine
        7z a ../Build.zip *.* -r
        cd ../
        cd _sdCard
        7z a ../Build.zip *.* -r
    - name: Make a release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "auto"
        prerelease: true
        title: "Auto Build"
        files: |
          Build.zip
