name: C/C++ CI

on:
  push:
    branches: [ WUT ]
  pull_request:
    branches: [ WUT ]

jobs:
  build_WUT:

    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest

    steps:
    - uses: actions/checkout@v2
    - name: Update permissions
      run: chmod +rwx build.sh
    - name: Build
      run: ./build.sh
    - name: Upload files
      uses: actions/upload-artifact@v2
      with:
        name: Binaries
        path : |
          _sdCard
          _loadiine
    - name: Install 7z
      run: |
          apt-get update
          apt-get install p7zip-full
    - name: Zip Files
      run: |
        cd _sdCard
        7z a ../Build.zip *.* -r
        cd ../
        cd _loadiine
        7z a ../Build.zip *.* -r
        cd ../
    - name: Upload Build.zip
      uses: actions/upload-artifact@v2
      with: 
        name: Zip
        path: Build.zip
          
  build_dynamic:
    needs: build_WUT
    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest
    
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dynamic_libs
      - run: make -j4
      - name: Get cache
        uses: actions/download-artifact@v2
        with:
          name: Zip
      - name: Install 7z
        run: |
          apt-get update
          apt-get install p7zip-full
      - name: Update Build.zip
        run: 7z a Build.zip WiiUFtpServer.elf
      - name: Make a release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "auto"
          prerelease: true
          title: "Auto Build"
          files: |
            Build.zip
      
