name: C/C++ CI

on:
  push:
    branches: [ WUT ]
  pull_request:
    branches: [ WUT ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkitppc:latest

    steps:
    - uses: actions/checkout@v2
    - name: Update permissions
      run: chmod +rwx build.sh
    - name: Build
      run: ./build.sh
    - name: Upload files
      uses: actions/upload-artifact@v2
      with:
        name: Build
        path : |
          _sdCard
          _loadiine
    - name: Zip Files
      uses: papeloto/action-zip@v1
      with:
          files: |
            _sdCard
            _loadiine
          dest: Build.zip
    - name: Make a release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "auto"
        prerelease: true
        title: "Auto Build"
        files: |
          Build.zip
